# Generated by Django 6.1.1 on 2026-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('roll_no', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feald', models.TextField(blank=True)),
            ],
        ),
    ]
