# Generated by Django 6.1.1 on 2026-09-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='student',
        ),
    ]
