# Generated by Django 6.1.1 on 2026-09-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruid', '0002_rename_invoice_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uniq_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
